<?php

declare(strict_types=1);

namespace Marko\Roadrunner\Exceptions;

use Marko\Core\Exceptions\MarkoException;

class BasePathNotResolvableException extends MarkoException
{
    public static function whenDirectoryMissing(
        string $path,
        string $missingDirectory,
        string $source,
    ): self {
        $resolved = $path === '' ? '(empty)' : $path;

        return new self(
            message: "Cannot resolve the application base path: '$resolved/$missingDirectory' does not exist.",
            context: "While resolving the base path from $source, before the worker can boot the application",
            suggestion: 'Set the MARKO_BASE_PATH environment variable to the project root — the default .rr.yaml '
                . "generated by 'rr:serve' already does this. Otherwise run the worker with a working directory "
                . 'that contains vendor/, app/ and modules/.',
        );
    }
}
